EnchantSystem = GetEnchantStrong();

EnchantSystem:ClearStrongMaterial()
EnchantSystem:SetStrongMaterial( KEnchantStrong.GEM,   8880 ) -- 젬(기본)
EnchantSystem:SetStrongMaterial( KEnchantStrong.CHOCO, 283460 ) -- 발렌타인 강화 초콜릿

EnchantSystem:ClearStrongAssistWeak()
EnchantSystem:SetStrongAssistWeak( 47970 ) -- 강화하락방지 아이템

EnchantSystem:ClearStrongLimitLevel()
EnchantSystem:SetStrongLimitLevel( 16 ) -- 강화 제한 레벨 설정.

EnchantSystem:ClearEnchantInfo()

EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE, KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE, KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE, KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE, KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE, KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE, KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE, KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE, KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE, KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0,  0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0,  0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.GEM,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0,  0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0,  0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level9, KEnchantStrong.GEM,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level9, KEnchantStrong.GEM, 100,  0, 0 )
-- 로즈목걸이
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level8, KEnchantStrong.GEM,   100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ROSE,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.FIRE,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ICE,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LOVE,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SHINE,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIGHT,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.WIND,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,  100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CASH_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GP_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,  100,  0, 0 )

--데스이터 목걸이
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level8, KEnchantStrong.GEM,   100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DEATH,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 )

--클로소 목걸이
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level8, KEnchantStrong.GEM,   100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TIME,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 )                                                                        
                                                                                            
--생명의 나무 목걸이
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level1, KEnchantStrong.GEM,   100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level2, KEnchantStrong.GEM,    100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level3, KEnchantStrong.GEM,    100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level4, KEnchantStrong.GEM,    100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level5, KEnchantStrong.GEM,    100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level6, KEnchantStrong.GEM,    100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level7, KEnchantStrong.GEM,    100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level8, KEnchantStrong.GEM,     100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIFE,  KEnchantStrong.Level9, KEnchantStrong.GEM,     100,  0, 0 )
			   
-- 붉은 흑룡의 목걸이
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level8, KEnchantStrong.GEM,   100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_RED,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 ) 

-- 푸른 흑룡의 목걸이
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level8, KEnchantStrong.GEM,   100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.DARK_DRAGON_BLUE,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 ) 

-- 사자 발찌
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,   KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0,  0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,   KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,   KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,   KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,   KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,   KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,   KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,   KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,   KEnchantStrong.Level9, KEnchantStrong.GEM,   100,  0, 0 ) 

EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LEO_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

-- 조로냥 발찌
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.GEM,   100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ZORRO_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 ) 

-- 천칭 발찌
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.GEM,   100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.LIBRA_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 ) 

-- 전갈 발찌
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )
                                               
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.GEM,   100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SCORPIO_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 ) 

-- 할로윈 목걸이
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level8, KEnchantStrong.GEM,   100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.HALLOWEEN,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 ) 

-- 사수자리 발찌
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )
                                               
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.GEM,   100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.SAGITTARIUS_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 ) 

-- 염소자리 발찌
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )
                                                    
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.GEM,   100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CAPRICORN_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 ) 

--물고기 자리
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.PISCES_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 )

-- 양자리 발찌
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,   KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0,  0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,   KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,   KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,   KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,   KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,   KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,   KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,   KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,   KEnchantStrong.Level9, KEnchantStrong.GEM,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ARIES_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

-- 황소자리 발찌
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,   KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0,  0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,   KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,   KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,   KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,   KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,   KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,   KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,   KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,   KEnchantStrong.Level9, KEnchantStrong.GEM,   100,  0, 0 ) 

EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.TAURUS_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

-- 쌍둥이 자리 발찌
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,   KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0,  0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,   KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,   KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,   KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,   KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,   KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,   KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,   KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,   KEnchantStrong.Level9, KEnchantStrong.GEM,   100,  0, 0 ) 

EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.GEMINI_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

-- 게자리 발찌
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,   KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0,  0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,   KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,   KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,   KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,   KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,   KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,   KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,   KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,   KEnchantStrong.Level9, KEnchantStrong.GEM,   100,  0, 0 ) 

EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.CANCER_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

-- 블랙 서펀트 목걸이
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level8, KEnchantStrong.GEM,   100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA,  KEnchantStrong.Level9, KEnchantStrong.GEM,  100,  0, 0 ) 

-- 블랙 서펀트 발찌 
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,   KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0,  0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,   KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,   KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,   KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,   KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,   KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,   KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,   KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,   KEnchantStrong.Level9, KEnchantStrong.GEM,   100,  0, 0 ) 

EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ELIA_ANKLE,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

-- 처녀 발찌
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,   KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0,  0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,   KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,   KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,   KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,   KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,   KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,   KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,   KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,   KEnchantStrong.Level9, KEnchantStrong.GEM,   100,  0, 0 ) 

EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.VIRGO_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

--[[
	Season Eternal: Tornozeleira de Aquario => Colar do Unicornio
	Season V: Colar do Unicornio => Tornozeleira de Aquario
--]]
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,   KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0,  0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,   KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,   KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,   KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,   KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,   KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,   KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,   KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,   KEnchantStrong.Level9, KEnchantStrong.GEM,   100,  0, 0 ) 

EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.AQUARIUS_SHIELD,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

--[[
	Season Eternal: Tornozeleira do 10º Aniversario => Tornozeleira do Unicornio
	Season V: Tornozeleira do Unicornio => Tornozeleira do 10º Aniversario
--]]
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,   KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0,  0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,   KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,   KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,   KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,   KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,   KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,   KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,   KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,   KEnchantStrong.Level9, KEnchantStrong.GEM,   100,  0, 0 ) 

EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_10TH,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

-- 차원의 문 발찌 							   	
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,   KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0,  0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,   KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,   KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,   KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,   KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,   KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,   KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,   KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,   KEnchantStrong.Level9, KEnchantStrong.GEM,   100,  0, 0 ) 
                                               
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_DIMENSION,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )

-- 페가수스 발찌 							   	
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,   KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0,  0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,   KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,   KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,   KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,   KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,   KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,   KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,   KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,   KEnchantStrong.Level9, KEnchantStrong.GEM,   100,  0, 0 ) 
                                                     
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.ANKLE_PEGASUS,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )


-- 페가수스 목걸이 							   	
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,   KEnchantStrong.Level1, KEnchantStrong.GEM, 100,  0,  0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,   KEnchantStrong.Level2, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,   KEnchantStrong.Level4, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,   KEnchantStrong.Level3, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,   KEnchantStrong.Level5, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,   KEnchantStrong.Level6, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,   KEnchantStrong.Level7, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,   KEnchantStrong.Level8, KEnchantStrong.GEM,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,   KEnchantStrong.Level9, KEnchantStrong.GEM,   100,  0, 0 ) 
                                               
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,  KEnchantStrong.Level1, KEnchantStrong.CHOCO, 100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,  KEnchantStrong.Level2, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,  KEnchantStrong.Level3, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,  KEnchantStrong.Level4, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,  KEnchantStrong.Level5, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,  KEnchantStrong.Level6, KEnchantStrong.CHOCO,  100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,  KEnchantStrong.Level7, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,  KEnchantStrong.Level8, KEnchantStrong.CHOCO,100,  0, 0 )
EnchantSystem:SetEnchantAction( KEnchantStrong.NECK_PEGASUS,  KEnchantStrong.Level9, KEnchantStrong.CHOCO,   100,  0, 0 )


EnchantSystem:ClearMaterialCount()
EnchantSystem:SetEnchantMaterialCount{ 1, 2, 2, 2, 2, 3, 3, 3, 3, }		-- 강화에 필요한 젬 수량

EnchantSystem:ClearAssistInfoTable()
--0 : SUCCESS, 1 : WEAKNESS, 2 : BREAK, 3 : NONE
EnchantSystem:AddStronAssist( 47970, KEnchantStrong.Level1, { {0, 2.0}, {1, 0.5} } )
EnchantSystem:AddStronAssist( 47970, KEnchantStrong.Level2, { {0, 2.0}, {1, 0.5} } )
EnchantSystem:AddStronAssist( 47970, KEnchantStrong.Level3, { {0, 2.0}, {1, 0.5} } )
EnchantSystem:AddStronAssist( 47970, KEnchantStrong.Level4, { {0, 2.0}, {1, 0.5} } )
EnchantSystem:AddStronAssist( 47970, KEnchantStrong.Level5, { {0, 2.0}, {1, 0.5} } )
EnchantSystem:AddStronAssist( 47970, KEnchantStrong.Level6, { {0, 2.0}, {1, 0.5} } )
EnchantSystem:AddStronAssist( 47970, KEnchantStrong.Level7, { {0, 2.0}, {1, 0.5} } )
EnchantSystem:AddStronAssist( 47970, KEnchantStrong.Level8, { {0, 2.0}, {1, 0.5} } )
EnchantSystem:AddStronAssist( 47970, KEnchantStrong.Level9, { {0, 2.0}, {1, 0.5} } )


--3에서 4가면서 부터 하락 존재
--6에서 7가면서 부터 초기화 존재
--9에서 10가면서 부터 초기화 존재

EnchantSystem:ClearEnchantLimitLv()
-- 인챈트시에 실패했을 경우의 액션을 세팅한다.
-- 0,1,2는 실패? 액션이 성공이다.
EnchantSystem:SetEnchantFailResult( 0, KEnchantStrong.SUCCESS )
EnchantSystem:SetEnchantFailResult( 1, KEnchantStrong.SUCCESS )
EnchantSystem:SetEnchantFailResult( 2, KEnchantStrong.SUCCESS )
EnchantSystem:SetEnchantFailResult( 3, KEnchantStrong.WEAKNESS )
EnchantSystem:SetEnchantFailResult( 4, KEnchantStrong.WEAKNESS )
EnchantSystem:SetEnchantFailResult( 5, KEnchantStrong.WEAKNESS )
EnchantSystem:SetEnchantFailResult( 6, KEnchantStrong.DROP )
EnchantSystem:SetEnchantFailResult( 7, KEnchantStrong.DROP )
EnchantSystem:SetEnchantFailResult( 8, KEnchantStrong.DROP )
for lv = 9, 120, 1 do
    EnchantSystem:SetEnchantFailResult( lv, KEnchantStrong.BREAK )
end


--                         [위는 각 실패했을때 액션과 확률을 나타낸다.]
--						   [성공의 경우는 실패 해도 성공이란 말이다.  ]


-- Grade, 시작레벨, 끝레벨, 하락, 초기화, 깨짐, 필요 강화아이템 증가량 및 초기값
EnchantSystem:SetEnchantRatio( KEnchantStrong.FIRST,	15, 34, 25, 50, 75, 1 )
EnchantSystem:SetEnchantRatio( KEnchantStrong.SECOND,	35, 54, 25, 50, 75, 2 )
EnchantSystem:SetEnchantRatio( KEnchantStrong.THIRD,	55, 75, 25, 50, 75, 3 )

EnchantSystem:SetCoreItemID( 58630 )
EnchantSystem:ClearEquipItemID()

EnchantSystem:AddEnchantEnableItemID( 56470	, 0 )
EnchantSystem:AddEnchantEnableItemID( 56480	, 0 )
EnchantSystem:AddEnchantEnableItemID( 56490	, 0 )
EnchantSystem:AddEnchantEnableItemID( 56500	, 0 )
EnchantSystem:AddEnchantEnableItemID( 56510	, 0 )
EnchantSystem:AddEnchantEnableItemID( 56520	, 0 )
EnchantSystem:AddEnchantEnableItemID( 56530	, 1 )
EnchantSystem:AddEnchantEnableItemID( 56540	, 1 )
EnchantSystem:AddEnchantEnableItemID( 56550	, 1 )
EnchantSystem:AddEnchantEnableItemID( 56560	, 1 )
EnchantSystem:AddEnchantEnableItemID( 56570	, 1 )
EnchantSystem:AddEnchantEnableItemID( 56580	, 1 )
EnchantSystem:AddEnchantEnableItemID( 56590	, 2 )
EnchantSystem:AddEnchantEnableItemID( 56600	, 2 )
EnchantSystem:AddEnchantEnableItemID( 56610	, 2 )
EnchantSystem:AddEnchantEnableItemID( 56620	, 2 )
EnchantSystem:AddEnchantEnableItemID( 56630	, 2 )
EnchantSystem:AddEnchantEnableItemID( 56640	, 2 )
EnchantSystem:AddEnchantEnableItemID( 56830	, 0 )
EnchantSystem:AddEnchantEnableItemID( 56840	, 0 )
EnchantSystem:AddEnchantEnableItemID( 56850	, 0 )
EnchantSystem:AddEnchantEnableItemID( 56860	, 0 )
EnchantSystem:AddEnchantEnableItemID( 56870	, 0 )
EnchantSystem:AddEnchantEnableItemID( 56880	, 0 )
EnchantSystem:AddEnchantEnableItemID( 56890	, 1 )
EnchantSystem:AddEnchantEnableItemID( 56900	, 1 )
EnchantSystem:AddEnchantEnableItemID( 56910	, 1 )
EnchantSystem:AddEnchantEnableItemID( 56920	, 1 )
EnchantSystem:AddEnchantEnableItemID( 56930	, 1 )
EnchantSystem:AddEnchantEnableItemID( 56940	, 1 )
EnchantSystem:AddEnchantEnableItemID( 56950	, 2 )
EnchantSystem:AddEnchantEnableItemID( 56960	, 2 )
EnchantSystem:AddEnchantEnableItemID( 56970	, 2 )
EnchantSystem:AddEnchantEnableItemID( 56980	, 2 )
EnchantSystem:AddEnchantEnableItemID( 56990	, 2 )
EnchantSystem:AddEnchantEnableItemID( 57000	, 2 )
EnchantSystem:AddEnchantEnableItemID( 57190	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57200	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57210	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57220	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57230	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57240	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57250	, 1 )
EnchantSystem:AddEnchantEnableItemID( 57260	, 1 )
EnchantSystem:AddEnchantEnableItemID( 57270	, 1 )
EnchantSystem:AddEnchantEnableItemID( 57280	, 1 )
EnchantSystem:AddEnchantEnableItemID( 57290	, 1 )
EnchantSystem:AddEnchantEnableItemID( 57300	, 1 )
EnchantSystem:AddEnchantEnableItemID( 57310	, 2 )
EnchantSystem:AddEnchantEnableItemID( 57320	, 2 )
EnchantSystem:AddEnchantEnableItemID( 57330	, 2 )
EnchantSystem:AddEnchantEnableItemID( 57340	, 2 )
EnchantSystem:AddEnchantEnableItemID( 57350	, 2 )
EnchantSystem:AddEnchantEnableItemID( 57360	, 2 )
EnchantSystem:AddEnchantEnableItemID( 57550	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57560	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57570	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57580	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57590	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57600	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57610	, 1 )
EnchantSystem:AddEnchantEnableItemID( 57620	, 1 )
EnchantSystem:AddEnchantEnableItemID( 57630	, 1 )
EnchantSystem:AddEnchantEnableItemID( 57640	, 1 )
EnchantSystem:AddEnchantEnableItemID( 57650	, 1 )
EnchantSystem:AddEnchantEnableItemID( 57660	, 1 )
EnchantSystem:AddEnchantEnableItemID( 57670	, 2 )
EnchantSystem:AddEnchantEnableItemID( 57680	, 2 )
EnchantSystem:AddEnchantEnableItemID( 57690	, 2 )
EnchantSystem:AddEnchantEnableItemID( 57700	, 2 )
EnchantSystem:AddEnchantEnableItemID( 57710	, 2 )
EnchantSystem:AddEnchantEnableItemID( 57720	, 2 )
EnchantSystem:AddEnchantEnableItemID( 57910	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57920	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57930	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57940	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57950	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57960	, 0 )
EnchantSystem:AddEnchantEnableItemID( 57970	, 1 )
EnchantSystem:AddEnchantEnableItemID( 57980	, 1 )
EnchantSystem:AddEnchantEnableItemID( 57990	, 1 )
EnchantSystem:AddEnchantEnableItemID( 58000	, 1 )
EnchantSystem:AddEnchantEnableItemID( 58010	, 1 )
EnchantSystem:AddEnchantEnableItemID( 58020	, 1 )
EnchantSystem:AddEnchantEnableItemID( 58030	, 2 )
EnchantSystem:AddEnchantEnableItemID( 58040	, 2 )
EnchantSystem:AddEnchantEnableItemID( 58050	, 2 )
EnchantSystem:AddEnchantEnableItemID( 58060	, 2 )
EnchantSystem:AddEnchantEnableItemID( 58070	, 2 )
EnchantSystem:AddEnchantEnableItemID( 58080	, 2 )
EnchantSystem:AddEnchantEnableItemID( 58270	, 0 )
EnchantSystem:AddEnchantEnableItemID( 58280	, 0 )
EnchantSystem:AddEnchantEnableItemID( 58290	, 0 )
EnchantSystem:AddEnchantEnableItemID( 58300	, 0 )
EnchantSystem:AddEnchantEnableItemID( 58310	, 0 )
EnchantSystem:AddEnchantEnableItemID( 58320	, 0 )
EnchantSystem:AddEnchantEnableItemID( 58330	, 1 )
EnchantSystem:AddEnchantEnableItemID( 58340	, 1 )
EnchantSystem:AddEnchantEnableItemID( 58350	, 1 )
EnchantSystem:AddEnchantEnableItemID( 58360	, 1 )
EnchantSystem:AddEnchantEnableItemID( 58370	, 1 )
EnchantSystem:AddEnchantEnableItemID( 58380	, 1 )
EnchantSystem:AddEnchantEnableItemID( 58390	, 2 )
EnchantSystem:AddEnchantEnableItemID( 58400	, 2 )
EnchantSystem:AddEnchantEnableItemID( 58410	, 2 )
EnchantSystem:AddEnchantEnableItemID( 58420	, 2 )
EnchantSystem:AddEnchantEnableItemID( 58430	, 2 )
EnchantSystem:AddEnchantEnableItemID( 58440	, 2 )
EnchantSystem:AddEnchantEnableItemID( 82120 , 0 )
EnchantSystem:AddEnchantEnableItemID( 82130 , 0 )
EnchantSystem:AddEnchantEnableItemID( 82140 , 0 )
EnchantSystem:AddEnchantEnableItemID( 82150 , 0 )
EnchantSystem:AddEnchantEnableItemID( 82160 , 0 )
EnchantSystem:AddEnchantEnableItemID( 82170 , 0 )
EnchantSystem:AddEnchantEnableItemID( 82180 , 1 )
EnchantSystem:AddEnchantEnableItemID( 82190 , 1 )
EnchantSystem:AddEnchantEnableItemID( 82200 , 1 )
EnchantSystem:AddEnchantEnableItemID( 82210 , 1 )
EnchantSystem:AddEnchantEnableItemID( 82220 , 1 )
EnchantSystem:AddEnchantEnableItemID( 82230 , 1 )
EnchantSystem:AddEnchantEnableItemID( 82240 , 2 )
EnchantSystem:AddEnchantEnableItemID( 82250 , 2 )
EnchantSystem:AddEnchantEnableItemID( 82260 , 2 )
EnchantSystem:AddEnchantEnableItemID( 82270 , 2 )
EnchantSystem:AddEnchantEnableItemID( 82280 , 2 )
EnchantSystem:AddEnchantEnableItemID( 82290 , 2 )

EnchantSystem:AddEnchantEnableItemID( 122020, 0 )
EnchantSystem:AddEnchantEnableItemID( 122030, 0 )
EnchantSystem:AddEnchantEnableItemID( 122040, 0 )
EnchantSystem:AddEnchantEnableItemID( 122050, 0 )
EnchantSystem:AddEnchantEnableItemID( 122060, 0 )
EnchantSystem:AddEnchantEnableItemID( 122070, 0 )
EnchantSystem:AddEnchantEnableItemID( 122080, 1 )
EnchantSystem:AddEnchantEnableItemID( 122090, 1 )
EnchantSystem:AddEnchantEnableItemID( 122100, 1 )
EnchantSystem:AddEnchantEnableItemID( 122110, 1 )
EnchantSystem:AddEnchantEnableItemID( 122120, 1 )
EnchantSystem:AddEnchantEnableItemID( 122130, 1 )
EnchantSystem:AddEnchantEnableItemID( 122140, 2 )
EnchantSystem:AddEnchantEnableItemID( 122150, 2 )
EnchantSystem:AddEnchantEnableItemID( 122160, 2 )
EnchantSystem:AddEnchantEnableItemID( 122170, 2 )
EnchantSystem:AddEnchantEnableItemID( 122180, 2 )
EnchantSystem:AddEnchantEnableItemID( 122190, 2 )


EnchantSystem:AddEnchantEnableItemID( 153570, 0 )
EnchantSystem:AddEnchantEnableItemID( 153580, 0 )
EnchantSystem:AddEnchantEnableItemID( 153590, 0 )
EnchantSystem:AddEnchantEnableItemID( 153600, 0 )
EnchantSystem:AddEnchantEnableItemID( 153610, 0 )
EnchantSystem:AddEnchantEnableItemID( 153620, 0 )
EnchantSystem:AddEnchantEnableItemID( 153630, 1 )
EnchantSystem:AddEnchantEnableItemID( 153640, 1 )
EnchantSystem:AddEnchantEnableItemID( 153650, 1 )
EnchantSystem:AddEnchantEnableItemID( 153660, 1 )
EnchantSystem:AddEnchantEnableItemID( 153670, 1 )
EnchantSystem:AddEnchantEnableItemID( 153680, 1 )
EnchantSystem:AddEnchantEnableItemID( 153690, 2 )
EnchantSystem:AddEnchantEnableItemID( 153700, 2 )
EnchantSystem:AddEnchantEnableItemID( 153710, 2 )
EnchantSystem:AddEnchantEnableItemID( 153720, 2 )
EnchantSystem:AddEnchantEnableItemID( 153730, 2 )
EnchantSystem:AddEnchantEnableItemID( 153740, 2 )

EnchantSystem:AddEnchantEnableItemID( 216640, 0 )
EnchantSystem:AddEnchantEnableItemID( 216650, 0 )
EnchantSystem:AddEnchantEnableItemID( 216660, 0 )
EnchantSystem:AddEnchantEnableItemID( 216670, 0 )
EnchantSystem:AddEnchantEnableItemID( 216680, 0 )
EnchantSystem:AddEnchantEnableItemID( 216690, 0 )
EnchantSystem:AddEnchantEnableItemID( 216700, 1 )
EnchantSystem:AddEnchantEnableItemID( 216710, 1 )
EnchantSystem:AddEnchantEnableItemID( 216720, 1 )
EnchantSystem:AddEnchantEnableItemID( 216730, 1 )
EnchantSystem:AddEnchantEnableItemID( 216740, 1 )
EnchantSystem:AddEnchantEnableItemID( 216750, 1 )
EnchantSystem:AddEnchantEnableItemID( 216760, 2 )
EnchantSystem:AddEnchantEnableItemID( 216770, 2 )
EnchantSystem:AddEnchantEnableItemID( 216780, 2 )
EnchantSystem:AddEnchantEnableItemID( 216790, 2 )
EnchantSystem:AddEnchantEnableItemID( 216800, 2 )
EnchantSystem:AddEnchantEnableItemID( 216810, 2 )

-- 디오 룬 아이템
EnchantSystem:AddEnchantEnableItemID( 339560, 0 )
EnchantSystem:AddEnchantEnableItemID( 339570, 0 )
EnchantSystem:AddEnchantEnableItemID( 339580, 0 )
EnchantSystem:AddEnchantEnableItemID( 339590, 0 )
EnchantSystem:AddEnchantEnableItemID( 339600, 0 )
EnchantSystem:AddEnchantEnableItemID( 339610, 0 )
EnchantSystem:AddEnchantEnableItemID( 339620, 1 )
EnchantSystem:AddEnchantEnableItemID( 339630, 1 )
EnchantSystem:AddEnchantEnableItemID( 339640, 1 )
EnchantSystem:AddEnchantEnableItemID( 339650, 1 )
EnchantSystem:AddEnchantEnableItemID( 339660, 1 )
EnchantSystem:AddEnchantEnableItemID( 339670, 1 )
EnchantSystem:AddEnchantEnableItemID( 339680, 2 )
EnchantSystem:AddEnchantEnableItemID( 339690, 2 )
EnchantSystem:AddEnchantEnableItemID( 339700, 2 )
EnchantSystem:AddEnchantEnableItemID( 339710, 2 )
EnchantSystem:AddEnchantEnableItemID( 339720, 2 )
EnchantSystem:AddEnchantEnableItemID( 339730, 2 )

-- 제로 룬 아이템
EnchantSystem:AddEnchantEnableItemID( 446010, 0 ) --낡은 용기의 룬
EnchantSystem:AddEnchantEnableItemID( 446020, 0 )
EnchantSystem:AddEnchantEnableItemID( 446030, 0 )
EnchantSystem:AddEnchantEnableItemID( 446040, 0 ) -- 용기의 룬
EnchantSystem:AddEnchantEnableItemID( 446050, 0 )
EnchantSystem:AddEnchantEnableItemID( 446060, 0 )
EnchantSystem:AddEnchantEnableItemID( 446070, 1 ) -- 낡은 축복의 룬
EnchantSystem:AddEnchantEnableItemID( 446080, 1 )
EnchantSystem:AddEnchantEnableItemID( 446090, 1 )
EnchantSystem:AddEnchantEnableItemID( 446100, 1 ) -- 축복의 룬
EnchantSystem:AddEnchantEnableItemID( 446110, 1 )
EnchantSystem:AddEnchantEnableItemID( 446120, 1 )
EnchantSystem:AddEnchantEnableItemID( 446130, 2 ) -- 낡은 영광의 룬
EnchantSystem:AddEnchantEnableItemID( 446140, 2 )
EnchantSystem:AddEnchantEnableItemID( 446150, 2 )
EnchantSystem:AddEnchantEnableItemID( 446160, 2 ) -- 영광의 룬
EnchantSystem:AddEnchantEnableItemID( 446170, 2 )
EnchantSystem:AddEnchantEnableItemID( 446180, 2 )

-- 레이 룬 아이템
EnchantSystem:AddEnchantEnableItemID( 525080, 0 ) --낡은 용기의 룬
EnchantSystem:AddEnchantEnableItemID( 525090, 0 )
EnchantSystem:AddEnchantEnableItemID( 525100, 0 )
EnchantSystem:AddEnchantEnableItemID( 525110, 0 ) -- 용기의 룬
EnchantSystem:AddEnchantEnableItemID( 525120, 0 )
EnchantSystem:AddEnchantEnableItemID( 525130, 0 )
EnchantSystem:AddEnchantEnableItemID( 525140, 1 ) -- 낡은 축복의 룬
EnchantSystem:AddEnchantEnableItemID( 525150, 1 )
EnchantSystem:AddEnchantEnableItemID( 525160, 1 )
EnchantSystem:AddEnchantEnableItemID( 525170, 1 ) -- 축복의 룬
EnchantSystem:AddEnchantEnableItemID( 525180, 1 )
EnchantSystem:AddEnchantEnableItemID( 525190, 1 )
EnchantSystem:AddEnchantEnableItemID( 525200, 2 ) -- 낡은 영광의 룬
EnchantSystem:AddEnchantEnableItemID( 525210, 2 )
EnchantSystem:AddEnchantEnableItemID( 525220, 2 )
EnchantSystem:AddEnchantEnableItemID( 525230, 2 ) -- 영광의 룬
EnchantSystem:AddEnchantEnableItemID( 525240, 2 )
EnchantSystem:AddEnchantEnableItemID( 525250, 2 )



EnchantSystem:ClearEnchantAssist()
EnchantSystem:AddEnchantAssistItem( 58700, 10 )
EnchantSystem:AddEnchantAssistItem( 71770, 15 )
EnchantSystem:AddEnchantAssistItem( 71780, 5 )
EnchantSystem:AddEnchantAssistItem( 85920, 10 )

