--[[
중국 적용할 활력 시스템 스크립트

작업자: 장상준, 이재준, 임지은, 정기섭, 곽재영

2013. 8. 15 수정
- 던전, 난이도별로 소모할 활력 수치 지정(기존: 항상 1 소모)
- 활력을 모두 소모한 상태로 플레이시 적용할 비율 설정 추가: EXP, GP, 게임드랍, 캐릭터게임드랍 비율(기존: 항상 0%비율 적용)

2013. 8. 26 수정
- 최초 캐릭터 생성시 지급하는 기본활력 수치 지정
- 최초를 제외한 나머지 캐릭터 생성시 지급하는 기본활력 수치 지정
--]]

UseVitalitySystem = FALSE

VitalityForFirstCharacterCreation = 260     -- 최초 캐릭터 생성시 지급하는 기본활력 수치
VitalityForCharacterCreation = 260          -- 최초를 제외한 나머지 캐릭터 생성시 지급하는 기본활력 수치
MaxVitalityPerDay = 260                     -- 활력 초기화 시간에 충전되는 기본활력 수치
VitalityPerRechargePoint = 10

VitalityCheckDungeon =
{
    { ModeID = GC_GM_QUEST0,  Difficulty = 0,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST0,  Difficulty = 1,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST0,  Difficulty = 2,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST1,  Difficulty = 0,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST1,  Difficulty = 1,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST1,  Difficulty = 2,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST2,  Difficulty = 0,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST2,  Difficulty = 1,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST2,  Difficulty = 2,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST3,  Difficulty = 0,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST3,  Difficulty = 1,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST3,  Difficulty = 2,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST4,  Difficulty = 0,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST4,  Difficulty = 1,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST4,  Difficulty = 2,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST5,  Difficulty = 0,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST5,  Difficulty = 1,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST5,  Difficulty = 2,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST6,  Difficulty = 0,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST6,  Difficulty = 1,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST6,  Difficulty = 2,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST7,  Difficulty = 0,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST7,  Difficulty = 1,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST7,  Difficulty = 2,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST8,  Difficulty = 0,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST8,  Difficulty = 1,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST8,  Difficulty = 2,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST9,  Difficulty = 0,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST9,  Difficulty = 1,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST9,  Difficulty = 2,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST10, Difficulty = 0,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST10, Difficulty = 1,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST10, Difficulty = 2,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST11, Difficulty = 0,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST11, Difficulty = 1,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST11, Difficulty = 2,   DeductVitality = 5,  RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST12, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST12, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST12, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST13, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST13, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST13, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST14, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST14, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST14, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST15, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST15, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST15, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST16, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST16, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST16, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST17, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST17, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST17, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST18, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST18, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST18, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST19, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST19, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST19, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST20, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST20, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST20, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST21, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST21, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST21, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST22, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST22, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST22, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST23, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST23, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST23, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST24, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST24, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST24, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST25, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST25, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST25, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST27, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST27, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST27, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST28, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST28, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST28, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST29, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST29, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST29, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST30, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST30, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST30, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST31, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST31, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST31, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST32, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST32, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST32, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST33, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST33, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST33, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST34, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST34, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST34, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST39, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST39, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST39, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST40, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST40, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST40, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST41, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST41, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST41, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST42, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST42, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST42, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST43, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST43, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST43, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST44, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST44, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST44, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST45, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST45, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST45, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST48, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST48, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST48, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST55, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST55, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST55, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST56, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST56, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST56, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    --[[
    { ModeID = GC_GM_QUEST59, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST59, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST59, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST60, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST60, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST60, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST61, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST61, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST61, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST62, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST62, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST62, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST63, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST63, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST63, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST65, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST65, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST65, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST66, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST66, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST66, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST67, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST67, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST67, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST68, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST68, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST68, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST69, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST69, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST69, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST70, Difficulty = 0,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST70, Difficulty = 1,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    { ModeID = GC_GM_QUEST70, Difficulty = 2,   DeductVitality = 10, RatioNoVitality = { EXP = 50, GP = 50, ItemDrop = 100, }, },
    --]]
}
