[Version]
Protocol Version 1 = 57
Protocol Version 2 = 36

[String]
str_01 = A autenticacao do gameguard falhou.
str_02 = O mesmo usuario esta logado em outro servidor.
str_03 = Falha ao gerar o GUID do hackshield.
str_04 = Falha na analise do GUID do HackShield.
str_05 = Falha ao gerar o pacote de autenticacao hackshield.
str_06 = Falha ao analisar o pacote de autenticacao do hackshield.
str_07 = Ocorreu um erro ao autenticar o hack.
str_08 = Obteve equipamento GrandChase PC e Guardian Ring.
str_09 = Coreia

[NMJAuth]				
str_00 = NexonNMJCoop

[Squares]
str_00 = [Plaza 1]
str_01 = [Plaza 2]
str_02 = [Plaza 3]
str_03 = [Plaza 4]
str_04 = [Plaza 5]
#str_05 = [Plaza 6]
#str_06 = [Plaza 7]
#str_07 = [Plaza 8]

[Mail]
str_00 = woosh@kog.co.kr
str_01 = tgkwon@kog.co.kr
str_02 = chivalries@kog.co.kr
