ScriptInfo = {
    ScriptFolder = "Script",

    FileList =
    {
        "ChatRecUIDList.lua",
        "DefaultReward.lua",
        "Dungeon_ExpGp.lua",
        "DungeonState.lua",
        "ExpGpBoostInfo.lua",
        "GameDrop.lua",
        "GameModeLevelInfo.lua",
        "InitChampion.lua",
        "InitChannelDrop.lua",
        "InitChannels.lua",
        "InitCTMission.lua",
        "InitDonationInfo.lua",
        "InitDrop.lua",
        "InitEnchant.lua",
        "InitGacha.lua",
        "InitGCHelper.lua",
        "InitGPCapsule.lua",
        "InitKairo.lua",
        "InitLunaNewYear.lua",
        "InitManufacture.lua",
        "InitMission.lua",
        "InitPetScript.lua",
        "InitPollInfo.lua",
        "InitPreHackCheck.lua",
        "InitRecom.lua",
        "InitReconcileInfo.lua",
        "InitSHCheck.lua",
        "InitSignBoardInfo.lua",
        "InitSkillInfo.lua",
        "InitSkillTree.lua",
        "InitSquare.lua",
        "InitTriggerInfo.lua",
        "InitVIPItemInfo.lua",
        "LevelLimit.lua",
        "RequierInfo.lua",
        "SquareInfo.lua",
        "weaponinfo.lua",
    }
}
